### 1. @RequestParam方式接收参数
GET http://localhost:8080/mySpringBoot/param/queryUser?usName=admin&pwd=123456&age=18
Accept: application/json

### 2. @PathVariable方式接收参数
GET http://localhost:8080/mySpringBoot/param/queryUserByAge/18
Accept: application/json

### 3. @RequestBody方式接收参数
POST http://localhost:8080/mySpringBoot/param/addUser
Content-Type: application/json

{
  "usName": "admin",
  "password": "123456",
  "age": "18"
}
